# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  pythonlint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install flake8
          command: sudo pip install --upgrade flake8
      - run:
          name: Python linter
          command: flake8
  yamllint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: sudo pip install --upgrade yamllint
      - run:
          name: Yaml linter
          command: yamllint .
  build:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_core
            python -m venv /tmp/venv/openfisca_core
            echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make install

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

      - run:
          name: Run Core tests
          command: make test

      - run:
          name: Run Country Template tests
          command: |
            NSW_PATH=`python -c "import openfisca_nsw; print(openfisca_nsw.CountryTaxBenefitSystem().get_package_metadata()['location'])"`
            openfisca-run-test --country openfisca_nsw $NSW_PATH/openfisca_nsw/tests/

  check_version_and_changelog:
    docker:
      - image: python:3.6
    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - pythonlint
      - yamllint
      - check_version_and_changelog
